### ISSUE TITLE
exporting new models from anno2070

### ISSUE THREAD

**Issue by marcussimmonscc** [lukts30/rdm4#118]
hello,

my apologies for my lack of knowledge/experience. 

i'm trying extract models from anno2070 complete edition (ubisoft player) but can't figure out how. i followed the video tutorial as best i could, but i don't see where the buildings are being extracted to in the game folders.  

I looked in data > graphics > --- but only see a "ui" folder, no "buildings" folder as pictured in the video.

**Comment by lukts30** [comment]
Building graphics are spread across data2.rda + patchX.rda + addon0.rda.
